### ISSUE TITLE
Replace default meta description tag

### ISSUE THREAD

**Issue by mapsam** [opendot/ml4a-invisible-cities#2]
Hey! This is a lovely project. 😄 

I saw this posted in a slack channel and noticed the meta `description` tag in the snippet was the default from the `_config.yml` file here: https://github.com/opendot/ml4a-invisible-cities/blob/gh-pages/_config.yml#L5-L8 - updating that would make sharing much friendlier.

<img width="517" alt="screen shot 2016-11-30 at 2 56 27 pm" src="https://cloud.githubusercontent.com/assets/1943001/20774879/3226a744-b70d-11e6-8b97-e3b08f08e079.png">

I'd be happy to update it - but I'm sure someone could write a better description than myself. Thanks!

**Comment by damianogui** [comment]
Thanks Sam, noted and updated!

**Comment by mapsam** [comment]
Lovely!
